services:
  postgres-db:
    image: postgres:16-alpine

  api:
    image: ghcr.io/matth-s/cesizen-back
    ports:
      - '3000:3000'
      - '5555:5555'
    depends_on:
      postgres-db:
        condition: service_healthy

  backoffice:
    image: ghcr.io/matth-s/cesizen-front
    ports:
      - '5173:5173'
    depends_on:
      - api

  mobile-app:
    image: ghcr.io/matth-s/cesizen-mobile
    ports:
      - '5174:5174'
    depends_on:
      - api
