services:
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - api
      - backoffice
      # - mobile-app

  api:
    image: ${MONO_PROJECT_BACK}:latest
    container_name: fastify_api
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL}
      - JWT_ACCESS_PRIVATE=${JWT_ACCESS_PRIVATE}
      - JWT_ACCESS_PUBLIC=${JWT_ACCESS_PUBLIC}
      - JWT_REFRESH_PRIVATE=${JWT_REFRESH_PRIVATE}
      - JWT_REFRESH_PUBLIC=${JWT_REFRESH_PUBLIC}
      - FRONTEND_URL=${AZURE_VM_IP}
    expose:
      - '3000'
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000',
        ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    env_file:
      - .env

  backoffice:
    image: ${MONO_PROJECT_FRONT}:latest
    container_name: vite_backoffice
    restart: always
    expose:
      - '5173'
    environment:
      - VITE_PUBLIC_API_ROUTE=http://${AZURE_VM_IP}/api
    depends_on:
      - api

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
    healthcheck:
      test:
        - CMD-SHELL
        - curl -fs http://localhost:9200 >/dev/null || exit 1
      interval: 10s
      timeout: 5s
      retries: 20
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.0
    container_name: kibana
    restart: always
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - '5601:5601'
    depends_on:
      elasticsearch:
        condition: service_healthy

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.17.0
    container_name: filebeat
    user: root
    restart: always

    command:
      - filebeat
      - -e
      - -c
      - /usr/share/filebeat/filebeat.yml

    volumes:
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
