services:
  backend:
    image: node:24-alpine
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydb?schema=public
      - DIRECT_URL=postgresql://myuser:mypassword@postgres-db:5432/mydb?schema=public
      - JWT_ACCESS_SECRET=0029f0d94e27afb24f4efedd8da
      - JWT_REFRESH_SECRET=b15637cd7d8030a83d20
      - FRONTEND_URL=http://127.0.0.1:5173
      - NODE_ENV=development
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_backend
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
