services:
  frontend:
    image: mcr.microsoft.com/playwright:v1.61.1-noble
    working_dir: /app
    ports:
      - '5173:5173'
    volumes:
      - ./backoffice:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"

    depends_on:
      - backend

  mobileApp:
    image: mcr.microsoft.com/playwright:v1.61.1-noble
    working_dir: /app
    ports:
      - '5174:5174'
    volumes:
      - ./user-front:/app
      - /app/node_modules
    command: sh -c "npm install && npx playwright install && npm run dev"

    depends_on:
      - backend

  backend:
    image: node:24-alpine
    working_dir: /app
    env_file:
      - ./backend/.env

    ports:
      - '3000:3000'
    volumes:
      - ./backend:/app
      - /app/node_modules
      - /var/run/docker.sock:/var/run/docker.sock
    command: sh -c "npm install && npm run dev"
    environment:
      - DATABASE_URL=postgresql://myuser:mypassword@postgres-db:5432/mydb?schema=public
      - NODE_ENV=development
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:16-alpine
    container_name: postgres_backend
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U myuser -d mydb']
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  postgres_data:
