sonar.organization=matth-s
sonar.projectKey=matth-s_cesizen_BACKEND
sonar.projectVersion=1.0.0
sonar.projectEncoding=UTF-8

sonar.language=js
sonar.sources=src
sonar.tests=src/__test__
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=node_modules/**,src/__test__/**

sonar.coverage.exclusions=node_modules/**,src/generated/**,src/types/**,dist,**/*.config.ts,**/*.d.ts,src/test-setup.ts,src/libs,src/plugins,src/routes,**/schemas/**
      
sonar.qualityGate.wait=false