export const stressQuizData = {
  title: 'Diagnostic de stress',
  answer: {
    create: [
      { name: 'Décès du conjoint', value: 100 },
      { name: 'Divorce', value: 73 },
      { name: 'Séparation', value: 65 },
      { name: 'Séjour en prison', value: 63 },
      { name: 'Décès d’un proche parent', value: 63 },
      { name: 'Maladies ou blessures personnelles', value: 53 },
      { name: 'Mariage', value: 50 },
      { name: 'Perte d’emploi', value: 47 },
      { name: 'Réconciliation avec le conjoint', value: 45 },
      { name: 'Retraite', value: 45 },
      {
        name: 'Modification de l’état de santé d’un membre de la famille',
        value: 44,
      },
      { name: 'Grossesse', value: 40 },
      { name: 'Difficultés sexuelles', value: 39 },
      { name: 'Ajout d’un membre dans la famille', value: 39 },
      { name: 'Changement dans la vie professionnelle', value: 39 },
      { name: 'Modification de la situation financière', value: 38 },
      { name: 'Mort d’un ami proche', value: 37 },
      { name: 'Changement de carrière', value: 36 },
      {
        name: 'Modification du nombre de disputes avec le conjoint',
        value: 35,
      },
      { name: 'Hypothèque supérieure à un an de salaire', value: 31 },
      { name: 'Saisie d’hypothèque ou de prêt', value: 30 },
      {
        name: 'Modification de ses responsabilités professionnelles',
        value: 29,
      },
      { name: 'Départ de l’un des enfants', value: 29 },
      { name: 'Problème avec les beaux-parents', value: 29 },
      { name: 'Succès personnel éclatant', value: 28 },
      { name: 'Début ou fin d’emploi du conjoint', value: 26 },
      { name: 'Première ou dernière année d’études', value: 26 },
      { name: 'Modification de ses conditions de vie', value: 25 },
      {
        name: 'Changements dans ses habitudes personnelles',
        value: 24,
      },
      { name: 'Difficultés avec son patron', value: 23 },
      {
        name: 'Modification des heures et des conditions de travail',
        value: 20,
      },
      { name: 'Changement de domicile', value: 20 },
      { name: 'Changement d’école', value: 20 },
      {
        name: 'Changement du type ou de la quantité de loisirs',
        value: 19,
      },
      { name: 'Modification des activités religieuses', value: 19 },
      { name: 'Modification des activités sociales', value: 18 },
      {
        name: 'Hypothèque ou prêt inférieur à un an de salaire',
        value: 17,
      },
      { name: 'Modification des habitudes de sommeil', value: 16 },
      {
        name: 'Modification du nombre de réunions familiales',
        value: 15,
      },
      { name: 'Modification des habitudes alimentaires', value: 15 },
      { name: 'Voyage ou vacances', value: 13 },
      { name: 'Noël', value: 12 },
      { name: 'Infractions mineures à la loi', value: 11 },
    ],
  },
};
