name: 01-1 - Integration - TEST

on: workflow_call

jobs:
  Backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Run Tests
        run: npm run test:coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: backend/coverage
          retention-days: 1

  Frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backoffice

    env:
      VITE_PUBLIC_API_ROUTE: http://localhost:3000/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backoffice/package-lock.json

      - name: Install dependencies
        working-directory: backoffice
        run: npm ci

      # - name: Install Playwright browsers
      #   working-directory: backoffice
      #   run: npx playwright install --with-deps

      - name: Run unit tests and coverage
        working-directory: backoffice
        run: npm run test:coverage

      # - name: Fix coverage paths for Sonar
      #   working-directory: backoffice
      #   run: sed -i 's|SF:'$(pwd)'/|SF:|g' coverage/lcov.info

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: admin-front-coverage-report
          path: backoffice/coverage
          retention-days: 1

      - name: Start frontend
        working-directory: backoffice
        run: |
          nohup npm run dev -- --host 127.0.0.1 > frontend.log 2>&1 &

      - name: Test Frontend
        run: curl --fail --retry 12 --retry-delay 5 --retry-connrefused http://127.0.0.1:5173

      # - name: Run E2E tests
      #   working-directory: backoffice
      #   run: npm run test:e2e

      # - name: Upload Playwright Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: admin-playwright-report
      #     path: backoffice/playwright-report
      #     retention-days: 1

  MobileApp:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: user-front

    env:
      VITE_PUBLIC_API_ROUTE: http://localhost:3000/api

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: user-front/package-lock.json

      - name: Install dependencies
        working-directory: user-front
        run: npm ci

      # - name: Install Playwright browsers
      #   working-directory: user-front
      #   run: npx playwright install --with-deps

      - name: Run unit tests and coverage
        working-directory: user-front
        run: npm run test:coverage

      # - name: Fix coverage paths for Sonar
      #   working-directory: user-front
      #   run: sed -i 's|SF:'$(pwd)'/|SF:|g' coverage/lcov.info

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mobile-coverage-report
          path: user-front/coverage
          retention-days: 1

      # - name: Run E2E tests
      #   working-directory: user-front
      #   run: npm run test:e2e

      # - name: Upload Playwright Report
      #   if: always()
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: mobile-playwright-report
      #     path: user-front/playwright-report
      #     retention-days: 1
