name: 01-1 - Integration - TEST

on: workflow_call

jobs:
  Backend:
    runs-on: ubuntu-latest

    services:
      postgres-db:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: myuser
          POSTGRES_PASSWORD: mypassword
          POSTGRES_DB: mydb
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      NODE_ENV: development
      DATABASE_URL: postgresql://myuser:mypassword@localhost:5432/mydb?schema=public

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Push prisma table to database
        run: npx prisma db push

      - name: Seed E2E Database
        working-directory: backend
        run: npm run seed:e2e

      - name: Run Tests
        run: npm run test:coverage

      - name: Upload Coverage Artifact
        uses: actions/upload-artifact@v4
        with:
          name: back-coverage-report
          path: backend/coverage
          retention-days: 1

  Frontend:
    needs: [Backend]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backoffice

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Start Backend & Postgres via Docker
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml up -d
          docker ps -a

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: backoffice/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Start Backend & Postgres via Docker
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml.yaml up -d
            
          sleep 15
          docker ps -a

      - name: Seed E2E Database
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml exec -T backend npm run seed:e2e

      - name: Install Playwright Browsers & Deps
        run: npx playwright install --with-deps

      - name: Curl backend
        run: curl http://localhost:3000/api/healt

      - name: Start frontend
        run: |
          nohup npm run dev -- --host 127.0.0.1 > frontend.log 2>&1 &

      - name: Wait for Frontend to be ready
        run: |
          curl --fail --retry 12 --retry-delay 5 --retry-connrefused http://127.0.0.1:5173

      - name: Run test end to end
        run: npm run test:e2e

        #  ajourt les tests unitaire avec le coverage si neccessaire

      - name: Clean Docker Containers
        if: always()
        run: |
          cd ..
          docker compose -f docker-compose-back-build.yml down -v
