name: 02-2 - Delivery - Trivy Scan

on: workflow_call

env:
  REGISTRY: ghcr.io
  USERNAME: ${{github.actor}}
  IMAGE_NAME: ${{github.repository}} #orga/repo

jobs:
  Trivy-Scan_Back:
    runs-on: ubuntu-22.04

    steps:
      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.PAT_TOKEN}}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Trivy Scan Back
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}-back
          format: table
          exit-code: '1'
          output: trivy-results-back.txt
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: ''

      - name: Upload Trivy report back
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-results-back
          path: trivy-results-back.txt
          retention-days: 1

  Trivy-Scan_Front:
    runs-on: ubuntu-22.04

    steps:
      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.PAT_TOKEN}}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Trivy Scan Front
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}-front
          format: table
          exit-code: '1'
          output: trivy-results-front.txt
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Upload Trivy report front
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-results-front
          path: trivy-results-front.txt
          retention-days: 1

  rivy-Scan_MOBILE:
    runs-on: ubuntu-22.04

    steps:
      - name: Registry login
        uses: docker/login-action@v3
        with:
          registry: ${{env.REGISTRY}}
          username: ${{env.USERNAME}}
          password: ${{secrets.PAT_TOKEN}}

      - name: Downcase Image Name
        run: echo "IMAGE_NAME_LOWER=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Trivy Scan Mobile
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: ${{env.REGISTRY}}/${{env.IMAGE_NAME_LOWER}}-mobile
          format: table
          exit-code: '1'
          output: trivy-results-mobile.txt
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL'

      - name: Upload Trivy report mobile
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-results-mobile
          path: trivy-results-mobile.txt
          retention-days: 1
