name: 02 - Stagging

on:
  push:
    branches:
      - develop
      - release/*

jobs:
  Build_Push_Docker:
    uses: ./.github/workflows/z_Docker-Ghcr.yml
    secrets: inherit

  Trivy_Scan_Package:
    needs: Build_Push_Docker
    uses: ./.github/workflows/02-2_TrivyScan.yml
    secrets: inherit

  Deploy:
    needs: Trivy_Scan_Package
    if: success()
    uses: ./.github/workflows/02-3_Deploy.yml
    with:
      environment: ${{ github.ref_name == 'develop' && 'staging' || 'production' }}
    secrets: inherit
    permissions:
      id-token: write
